apiVersion: v1
appVersion: v2.20.1
description: A Helm chart for Deploying Jumpserver on Kubernetes
home: https://jumpserver.org
icon: https://jumpserver.org/images/logo/favicon.ico
maintainers:
- email: support@fit2cloud.com
  name: jumpserver
name: jumpserver
sources:
- https://github.com/jumpserver/
version: 2.20.1
