apiVersion: v2
appVersion: "12.4"
dependencies:
- condition: postgresql.bundled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: ^12.1.6
- condition: memcached.bundled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: ^6.3.2
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: ^2.2.2
description: A Helm chart for running OpenProject via Kubernetes
home: https://www.openproject.org/
icon: https://www.openproject.org/assets/images/press/openproject-icon-original-color-41055eb6.png
maintainers:
- name: OpenProject
  url: https://github.com/opf/helm-charts
name: openproject
type: application
version: 1.4.0
