{{- if .Values.services.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis-service
  name: redis-service
spec:
  replicas: {{ .Values.services.redis.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: redis-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redis-service
    spec:
      containers:
      - args:
        - redis-server 
        - --requirepass 
        - {{ .Values.services.redis.password }}
        image: dhub.kubesre.xyz/library/redis
        imagePullPolicy: ""
        name: redis-service
        ports:
        - containerPort: {{ .Values.services.redis.port }}
        {{ with .Values.services.redis.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{ end }}
        volumeMounts:
        - mountPath: /data
          name: redis-data
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /etc/timezone
          name: timezone
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{ if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{ end }}
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{ end }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: ''
        name: localtime
      - hostPath:
          path: /etc/timezone
          type: ''
        name: timezone
status: {}
{{- end }}
