apiVersion: v1
kind: PersistentVolume
metadata:
  name: joget-community-pv
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joget-community-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joget-community
  labels: 
    app: joget-community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joget-community
  template:
    metadata:
      labels: 
        app: joget-community
    spec:
      volumes:
        - name: joget-community-pv
          persistentVolumeClaim:
            claimName: joget-community-pvc
      securityContext:
        runAsUser: 1000
        fsGroup: 0
      containers:
        - name: joget-community
          image: jogetworkflow/joget-community:7.0.27
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: joget-community-pv
              mountPath: /opt/joget/wflow
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                    fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: joget-community
  labels:
    app: joget-community
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 9080
    targetPort: 9080  
  selector:
    app: joget-community
  type: NodePort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: joget-community-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---              
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: joget-community-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: joget-community
              servicePort: 8080
       
