adminUsername: admin
affinity: {}
allowAdminParty: false
annotations: {}
clusterSize: 3
couchdbConfig:
  chttpd:
    bind_address: any
    require_valid_user: false
createAdminSecret: true
dns:
  clusterDomainSuffix: cluster.local
enableSearch: false
erlangFlags:
  name: couchdb
  setcookie: monster
image:
  pullPolicy: IfNotPresent
  repository: couchdb
  tag: 3.1.0
ingress:
  annotations: []
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: null
initImage:
  pullPolicy: Always
  repository: busybox
  tag: latest
livenessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
networkPolicy:
  enabled: true
persistentVolume:
  accessModes:
  - ReadWriteOnce
  enabled: false
  size: 10Gi
podManagementPolicy: Parallel
readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
resources: {}
searchImage:
  pullPolicy: IfNotPresent
  repository: kocolosk/couchdb-search
  tag: 0.2.0
service:
  enabled: true
  externalPort: 5984
  type: ClusterIP
serviceAccount:
  create: true
  enabled: true
sidecars: {}
tolerations: []
