apiVersion: v2
appVersion: 1.0.48
dependencies:
- condition: services.couchdb.enabled
  name: couchdb
  repository: https://apache.github.io/couchdb-helm
  version: 3.3.4
- condition: ingress.nginx
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.0.13
description: Budibase is an open source low-code platform, helping thousands of teams
  build apps for their workplace in minutes.
keywords:
- low-code
- database
- cluster
name: budibase
sources:
- https://github.com/Budibase/budibase
- https://budibase.com
type: application
version: 0.2.8
